### ISSUE TITLE
Slack formatting

### ISSUE THREAD

**Issue by mikestreety** [federicot/hubot-pagespeed#1]
Appreciate this was originally developed for another client, but would be good if it could use the adapter to work out formatting?

rather than "quote", it would be good if for Slack it could do three back ticks, before and after (```)

(see screenshots :) ) 

Will have a look myself to see if I can work it out!

Before:
![screen shot 2015-03-26 at 14 07 41](https://cloud.githubusercontent.com/assets/354085/6847871/92ecc878-d3c1-11e4-8259-bb7a58993957.png)

After:
![screen shot 2015-03-26 at 14 08 14](https://cloud.githubusercontent.com/assets/354085/6847870/92ebdfa8-d3c1-11e4-8b3d-0da488005cd3.png)

**Comment by mikestreety** [comment]
Looks like you can access the adater type in the script https://github.com/github/hubot/pull/663/files

**Comment by mikestreety** [comment]
Something like this seems to work:

Line 33:

``````
var format_start;
var format_end;

switch(robot.adapterName) {
    case 'slack':
        format['start'] = '```';
        format['end'] = '```';
        break;
    case 'shell':
        format_start = ' ';
        format_end = ' ';
        divider = ' ';
        break;
    default:
        format_start = '/quote';
        format_end = ' ';
} 
``````

Then change the ouput to 

```
output = [
    format_start,
    divider,
    generateScore(data.id, strategy, data.score),
    format_end
].join('\n');
msg.send(output);
```

**Comment by federicot** [comment]
Done. https://github.com/federicot/hubot-pagespeed/commit/95110c419f2c5657af864c45725d66536a9a1fe2

**Comment by mikestreety** [comment]
Thanks for this - mind `npm` tagging and publishing? :smile:

**Comment by mikestreety** [comment]
Nudge on this :smile:

**Comment by federicot** [comment]
Done

**Comment by mikestreety** [comment]
Thanks!!
